# Generated by Django 4.1.7 on 2023-02-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataReceived', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databet',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
